name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on: [pull_request]
jobs:
  Deploy-PR-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Branch name
        run: echo Branch was set to ${{ steps.extract_branch.outputs.branch }}
      - name: Run find-and-replace to remove slashes in branch names
        uses: mad9000/actions-find-and-replace-string@3
        id: findandreplace
        with:
          source: ${{ steps.extract_branch.outputs.branch }}
          find: '/'
          replace: '-'
      - name: Truncate to the max length
        uses: bhowell2/github-substring-action@1.0.2
        id: truncation
        with:
          value: ${{ steps.findandreplace.outputs.value }}
          length_from_start: 34
      - name: Set Alias URL
        run: echo "ALIAS_URL=$(echo home-git-${{ steps.truncation.outputs.substring }}-housecure.vercel.app)" >> $GITHUB_ENV
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Add Environment variable
        # you might want to remove the ${{ steps.extract_branch.outputs.branch }} part if you do not want to assign this to a specific branch but to ALL preview deployments
        run: echo ${ALIAS_URL} | vercel env add BACKEND_DOMAIN preview ${{ steps.extract_branch.outputs.branch }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: vercel deploy -m githubCommitRef=${{ steps.extract_branch.outputs.branch }} -m githubDeployment="1" -m githubCommitRepo=${{ github.repository }} --token=${{ secrets.VERCEL_TOKEN }} >> vcurl.txt
      - name: Read Vercel Deployment URL
        id: readfile
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: vcurl.txt
      - name: Update aliasurl.txt
        run: echo Preview URL - https://${ALIAS_URL} >> aliasurl.txt
      - name: Aliasing the URL
        run: vercel alias set ${{ steps.readfile.outputs.content }} ${ALIAS_URL} --token=${{ secrets.VERCEL_TOKEN }} --scope=vercel-support
      # This comments the deployment url on a Pull Request
      - name: Comment the URL on the PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: output_url
          filePath: aliasurl.txt
